#! /bin/sh

relnum=$1
if [ -z "$relnum" ]
then
  echo "Syntaxe: $0 release-number"
  exit 1
fi

version=`./scripts/version`
VERNUM=${version}.${relnum}

echo "Creating image Advene-${VERNUM}.dmg"

/usr/bin/hdiutil create -fs HFS+ -format UDZO -imagekey zlib-level=9 -srcfolder dist/Advene.app  -volname Advene-${VERNUM} Advene-${VERNUM}.dmg
