.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ADVENE 1 "March  7, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
advene \- Annotate DVds, Exchange on the NEt
.SH SYNOPSIS
.B advene
.SH DESCRIPTION
\fBadvene\fP is a program that permits to annotate a DVD and visualize
the annotations.

No documentation exists for the moment. You can try to launch the
program and try to make sense of the menu items. Use the --help option
to get a list of command line options.

User documentation is available from the website
http://liris.cnrs.fr/advene/wiki/index.php/Main_Page

.SH AUTHOR
This manual page was written by Olivier Aubert <olivier.aubert@liris.cnrs.fr>,
for the Debian project (but may be used by others).
