name: Advene dev testing workflow

on:
  push:
    branches:
      - dev

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git

      - name: "Build package"
        shell: msys2 {0}
        run: |
          cd dev/win_installer
          ./build.sh
          cd ../..
          ARTIFACT_PATHNAME=$(ls dev/win_installer/advene-*-installer.exe | head -n 1)
          ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME)
          echo "ARTIFACT_PATHNAME=${ARTIFACT_PATHNAME}" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

      - name: "Upload binary as artifact"
        uses: actions/upload-artifact@v2
        with:
          name: advene-dev
          path: dev/win_installer/advene-*-installer.exe
